### ISSUE TITLE
State changing bugs

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#142] opened 2023-04-26 08:47 UTC
Ideally we get tests for these, but that's an upfront investment in figuring out how to mock some of the interactions.

- [ ] While in edit geometry mode, click "Clear all"
- [ ] While in edit geometry mode, load another geojson file
- [ ] While a form is open, clear all. Hover briefly breaks

I can't reproduce it, but "split route" and "edit geometry" on an existing scheme were warping to the object when clicked, as if "edit attributes" was partially active

**Comment by Pete-Y-CS** [comment] 2023-05-18 09:48
Hey, looking to investigate this while I wait for Docker solutions: I suppose our expected behaviour is to disable buttons/actions that don't make sense according to the state we're in?

So for example for
> While in edit geometry mode, click "Clear all"
Would we like to disable the clear all button, or have it clear what we're working on?

Likewise I guess for this:
> While in edit geometry mode, load another geojson file
My instinct would be disabling the feature.

Not sure what is meant by:
> While a form is open, clear all. Hover briefly breaks
&
> I can't reproduce it, but "split route" and "edit geometry" on an existing scheme were warping to the object when clicked, as if "edit attributes" was partially active

Cheers

**Comment by dabreegster** [comment] 2023-05-18 09:57
> While in edit geometry mode, click "Clear all"
> Would we like to disable the clear all button, or have it clear what we're working on?

I'm not sure what behavior we should go for. Right now, it breaks `GeometryMode.svelte` with `feature is undefined`, because suddenly we're editing geometry of a feature ID that's vanished. "Clear all" is meant to totally erase the entire loaded file. So either we disable the button in certain modes, or when we do clear everything, we reset the drawing mode to "Edit attributes". Which do you think would be more intuitive to the user?

> While a form is open, clear all. Hover briefly breaks

I think I actually fixed that one in https://github.com/acteng/atip/commit/4534c3a5f7113bbfff8ee68a68d4e3d2b81651a8 (and with `tests/modes.spec.ts`!). The outline effect from `HoverLayer.svelte` was sticking around after clearing, until clicking the map again.

> I can't reproduce it, but "split route" and "edit geometry" on an existing scheme were warping to the object when clicked, as if "edit attributes" was partially active

Sometimes when I activate "split route" and click a route, it would open the form for that route and warp to it -- as if "edit attributes" was active. I haven't been able to reliably repro this one. I _think_ I've only seen it when developing locally, and I suspect it's related to #174

**Comment by dabreegster** [comment] 2023-05-18 09:58
For the first few problems, there's a general UX question. When changing between Toolbox tools, should we warn the user before work is lost? For example if you click "New route", draw a bunch of stuff, and then click "Edit attributes" or another button without clicking "Finish", you lose your route without warning. Before leaving a mode, we could act like the user has confirmed/saved that thing, or we could warn them?

**Comment by Pete-Y-CS** [comment] 2023-05-18 10:04
Yeah I suppose this might be a good opportunity to introduce a modal system for notifying users? In the above cases I guess it would be pretty simply something like "Are you sure, you'll lose your unsaved progress?" but if we have a nice svelte component for this I guess it would get some decent use

**Comment by dabreegster** [comment] 2023-05-18 11:05
+1 to that. We're using `window.confirm` right now before "Clear all" happens; probably something much nicer to use

**Comment by Pete-Y-CS** [comment] 2023-05-25 15:39
@dabreegster @Sparrow0hawk 
I've done an initial pass at a confirmation modal. Definitely could be tidied up so could be worth an interim review. Will put up a WIP PR.

However this doesn't directly address any of the the actual bugs in question. For that I think we might want to consider a bit of a restructure so we can use: https://svelte.dev/tutorial/writable-stores. If I'm not mistaken, for e.g. `EntireScheme:clearAll` to know about the state of e.g. `RouteMode` we're gonna want to put some amount of the current state of the app into a store which can be accessed and listened to at various points in the component hierarchy. In this case clear all needs to be able to clear any state associated with the current route being edited, and to change `Toolbox:mode` back to the default `'edit-attribute'`

Does this make sense? Definitely wanna get some second opinions on this one since it's quite a significant refactor but I think it makes sense here

**Comment by dabreegster** [comment] 2023-05-25 15:47
Lifting some of the local state into a global store sounds OK to me. What state did you have in mind? Maybe [mode in Toolbox](https://github.com/acteng/atip/blob/ea614c51f91727a4dff3542cf812482bc57bdb31/src/lib/draw/Toolbox.svelte#L37)? And what approach do we want to go for from the user's perspective?

1) while not in "edit attributes" mode, totally disable the "clear all" and "load geojson" and similar buttons that would interrupt the current operation?
2) if we clear or load a new file, force the mode back to "edit attributes", with or without some kind of confirmation modal?

I guess either way, a store for the drawing mode will make sense

**Comment by dabreegster** [comment] 2023-05-25 15:49
About the 1st option -- it's still a bit confusing that you can do stuff with the intervention list in the sidebar, like hover or open another object. Should we also disable all of that while in another draw tool?

https://github.com/acteng/atip/assets/1664407/0166d033-e28d-40e8-91e5-3f7bca476726

**Comment by Pete-Y-CS** [comment] 2023-05-25 15:51
I suppose just disabling the sidebar whilst you're editing the geometry would resolve the issue. It's a simple solution for now that probably makes sense anyway. I still feel like a memory store might be useful for extracting some logic from our svelte components, which would probably be nice to have anyway, but definitely could be a separate issue.

**Comment by Pete-Y-CS** [comment] 2023-05-25 15:53
Happy to go with the simpler option for now: disable most other things whenever you're editing anything, and shelve the modal and potential state store work for now

**Comment by Pete-Y-CS** [comment] 2023-05-25 15:54
Although I suppose, as I say that, that disabling other tools whilst editing certain thing probably requires a state store of some kind. At least some kind of semaphore/lock type thing for editing

**Comment by dabreegster** [comment] 2023-05-25 15:58
I think we could still use a store to know what drawing mode we're in, so that all the sidebar stuff can do stuff like `disabled={$mode != "edit-attributes"}` (or we use a derived store to clean that query up).

Also, the confirmation modal is worth keeping! It already has a nicer UI than `window.confirm`. No matter what, warning people before clearing seems nice to keep

**Comment by Pete-Y-CS** [comment] 2023-05-25 16:05
Alright, I'll look into doing something like the above to disable any not-in-use edit tools until the current tool is finished

**Comment by dabreegster** [comment] 2023-05-25 16:08
Relatedly, the other draw tools are always listening to every events, but immediately choosing to ignore it if they're not the active mode. In a sense, we're trying to do the same kind of thing, but for all the sideabar actions. But if you can think of a nicer way to make a draw tool "go to sleep" than this, happy for ideas:
https://github.com/acteng/atip/blob/ea614c51f91727a4dff3542cf812482bc57bdb31/src/lib/draw/polygon/polygon_tool.ts#L179

**Comment by robinlovelace-ate** [comment] 2023-06-05 11:18
This is 'nice-to-have' and in V2. Can we shift to v3 and close the milestone? https://github.com/acteng/atip/milestones/v2

**Comment by dabreegster** [comment] 2023-06-05 11:19
Yes, we've solved this bug adequately for v2. I'll reassign the milestone to v3 now

**Comment by robinlovelace-ate** [comment] 2023-06-05 11:27
🎉 

And I've tidied up by closing up the v2 milestone https://github.com/acteng/atip/milestone/2 🚿

**Closed** 2023-06-16 07:25 UTC
Labels: good first issue, release-nicetohave
