### ISSUE TITLE
Add dedicated crossings identification functionality

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#137] opened 2023-04-24 09:38 UTC
As outlined by @chris-ate this could be a priority. 

Reasoning:

- Crossings represent a major pinch point for active travel, especially for walking, and especially affecting less confident people e.g. school pupils
- The majority of walking and cycling crashes happen at junctions in many places

Thoughts on user story

- [ ] When sketching a new route it would be interesting to see the minimum number of times people have to cross a junction along the route
- [ ] Crossings could pop-up automatically or maybe less-intrusively after the user opts in
- [ ] Visual differentiation between crossing types, e.g. different colours, could help give an indication of severity of the crossing, with highway type being a reasonable starting point

In terms of how that could look, imagine sketching the top path in the route below, it would be useful to flag that there are many crossings, meaning many opportunities for left-hook crashes.

![image](https://user-images.githubusercontent.com/122299965/236026597-66c9eb11-b7f1-47ed-ad05-4388f40c3848.png)

Source: https://www.openstreetmap.org/relation/6386965#map=17/53.80788/-1.64609

**Comment by dabreegster** [comment] 2023-05-03 14:40
Any more context here?

**Comment by robinlovelace-ate** [comment] 2023-05-03 19:36
> Any more context here?

Just added 👍

**Comment by dabreegster** [comment] 2023-05-04 13:23
Thanks! This sounds like a good thing to tack onto the wishlist in #69. That issue has ideas and a prototype for how to implement it. We have to make some UX and data storage choices that're a bit interesting... for example, after we draw a route (which is recorded in the GeoJSON file) and we calculate crossings with a bunch of metadata, should we save that in the geojson file too? Or recalculate it later, treating it like a contextual layer?

**Comment by dabreegster** [comment] 2024-11-25 15:52
Dupe of #480

**Closed by dabreegster** 2024-11-25 15:52 UTC
