### ISSUE TITLE
Issue uploading a .txt file

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#72] opened 2023-02-09 10:47 UTC
As reported via email there is a reproducible upload issue shown below.

![image](https://user-images.githubusercontent.com/122299965/217791208-58fb94dc-aff8-49e1-894d-5533c9a52514.png)

Reproducible example: navigate to https://atip.uk/scheme.html?authority=Norfolk#8.45/52.673/0.949 and upload the attached file.
[Norfolk_scheme 2 Dereham Quebec Rd.txt](https://github.com/acteng/atip/files/10696227/Norfolk_scheme.2.Dereham.Quebec.Rd.txt)

**Comment by robinlovelace-ate** [comment] 2023-02-09 10:52
I have tried to reproduce the issue with a simple file but cannot. See attached minimal example.
[Uploading Norfolk.txt…]()

**Comment by PhillReilly** [comment] 2023-02-09 11:14
tried again with this file and still not working
[Norfolk_Scheme 2 B1146 Quebec Rd Dereham.txt](https://github.com/acteng/atip/files/10696448/Norfolk_Scheme.2.B1146.Quebec.Rd.Dereham.txt)

**Comment by dabreegster** [comment] 2023-02-09 11:18
I can reproduce the failure. That file is failing [checkOrigin](https://github.com/acteng/atip/blob/84e37a50e25f111c1a6ab2003347db3609b33397/components/EntireScheme.svelte#L68). It doesn't have an `authority` or `origin` property at the top level of the JSON object.

@PhillReilly, did you produce this file with ATIP, or another program?

**Comment by PhillReilly** [comment] 2023-02-09 11:22
i used ATIP with link from active travel england - i plotted the object named and saved, then exported to GeoTSON and saved the text file produced.  then try to reload it form the saved location (its a networked drive rather than laptop desktop) and the error appears - ju
![image](https://user-images.githubusercontent.com/124881576/217799267-295da1eb-e235-4056-9547-009f23252626.png)
st tried again to no avail

**Comment by PhillReilly** [comment] 2023-02-09 11:24
odd that this one works
[Norfolk_B1370 Church Lane 6th From College.txt](https://github.com/acteng/atip/files/10696533/Norfolk_B1370.Church.Lane.6th.From.College.txt)

**Comment by PhillReilly** [comment] 2023-02-09 11:25
browser is MS edge

**Comment by robinlovelace-ate** [comment] 2023-02-09 11:25
```
  "authority": "Norfolk",
  "origin": "atip-v1"
```

Add those new lines in the final 2 lines just before

```
}
```

And I predict: it will work 🤞

**Comment by robinlovelace-ate** [comment] 2023-02-09 11:26
Still: I think upload should work without the authority and origin info. Any reason not to?

**Comment by PhillReilly** [comment] 2023-02-09 11:29
now trying adding thos lines .. ill let you know in 2! - nope! guess i put in in the wron place - put at th every bottom before the last bracket

![image](https://user-images.githubusercontent.com/124881576/217800619-c074f49d-8444-4f59-a754-0b10743b31a9.png)

**Comment by PhillReilly** [comment] 2023-02-09 11:36
ok got it to work! i had to paste in "authority": "Norfolk", after scheme name at bottom and all good

**Comment by Robinlovelace** [comment] 2023-02-09 11:37
> ok got it to work! i had to paste in "authority": "Norfolk", after scheme name at bottom and all good

:tada:

**Comment by dabreegster** [comment] 2023-02-09 11:38
Awesome! There's still a bug lurking somewhere here -- ATIP export should've included those fields in the first place. We'll check into it before closing this issue.

**Comment by Robinlovelace** [comment] 2023-02-09 11:39
> Awesome! There's still a bug lurking somewhere here -- ATIP export should've included those fields in the first place. We'll check into it before closing this issue.

Thoughts on removing the need for authority and origin? I see that as a broader and potentially quicker fix.

**Comment by robinlovelace-ate** [comment] 2023-02-09 11:43
Agreed but the input in this case is not junk. I think other solutions with fewer impacts could address that. Also that issue is less important from user perspective than this one I think.

**Comment by Sparrow0hawk** [comment] 2023-02-13 11:56
Stumbled upon this but this issue is caused by creating an intervention, then clearing it which seems to remove "origin" and "authority".

This function maybe a bit too harsh? https://github.com/acteng/atip/blob/7e3ea66fc3d93e2c159db84f60436ba0fa4ef54d/components/EntireScheme.svelte#L26-L34

**Comment by Robinlovelace** [comment] 2023-02-14 11:19
Confirmation that this is a priority issue: 

> We have been having issues with ATIP when re-loading scheme maps once created. ATIP claims that they are not ATIP GeoJSON compatible even though they were created using the software. This doesn't happen with every map, but around half of them and there does not appear to be a pattern. Has anyone else had this issue? Could this be passed on to the mapping team. 

With 6 upvotes in session today.

**Comment by Robinlovelace** [comment] 2023-02-14 11:19
Can we deploy this fix @dabreegster ? Then we can close this issue I think.

**Comment by Robinlovelace** [comment] 2023-02-14 11:24
Got some upvotes on my reply saying this will be fixed too!

![image](https://user-images.githubusercontent.com/1825120/218723426-f7c62db3-54db-4ad4-a83c-c15f1304205c.png)

**Comment by Robinlovelace** [comment] 2023-02-15 11:41
I think this issue, that valid data in the original post, cannot be upload. Just checked now: https://github.com/acteng/atip/pull/80#issuecomment-1431231850

**Comment by Robinlovelace** [comment] 2023-02-15 12:45
Fixed by #81 and tested on dev.

After it's updated on production we can finally close this issue.

**Comment by dabreegster** [comment] 2023-02-15 12:46
Production has been deployed; it should be fixed everywhere now

**Comment by Robinlovelace** [comment] 2023-02-15 13:07
:tada:

**Closed by Robinlovelace** 2023-02-15 13:07 UTC
