### ISSUE TITLE
Update with new fields and possible values from agreed taxonomy of active travel interventions

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#117] opened 2023-04-11 20:34 UTC
Split out from #11 and linked to https://github.com/acteng/schema. After this issue is complete users will see new user inputs with the type of info requested depending on the intervention type. I believe there is already a branch that goes in some way in that direction.

**Comment by dabreegster** [comment] 2023-10-02 13:19
Dupe of #231

**Closed by dabreegster** 2023-10-02 13:19 UTC
