### ISSUE TITLE
Allowing users to select intervention types from the ATF4 guidance

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#242] opened 2023-06-19 16:07 UTC
- [ ] New segregated cycling facility
- [ ] New junction treatment
- [ ] New permanent footway
- [ ] New shared use (walking and cycling) facilities
- [ ] Improvements to make an existing walking/cycle route safer
- [ ] Area-wide traffic management (including by TROs - both permanent and experimental)
- [ ] Bus priority measures that also enable active travel (for example, bus gates)
- [ ] Provision of secure cycle parking facilities
- [ ] New road crossings
- [ ] Restriction or reduction of car parking availability
- [ ] School streets

<details>

- New segregated cycling facility
    - Sub-category: High complexity
        - What does this scheme sub-category look like? Urban, high density, complex junctions, side roads
        - How will this be measured? Miles of cycle route, number of junctions

    - Sub-category: Medium complexity
        - What does this scheme sub-category look like? Suburban, medium density, fewer junctions/turning movements
        - How will this be measured? Miles of cycle route, number of junctions

    - Sub-category: Low complexity
        - What does this scheme sub-category look like? Out of town location, low density, few/no junctions
        - How will this be measured? Miles of cycle route, number of junctions

- New junction treatment
    - Sub-category: High complexity
        - What does this scheme sub-category look like? Separation in time and space for all active travel movements, protected junctions.
        - How will this be measured? Junctions treated

    - Sub-category: Medium complexity
        - What does this scheme sub-category look like? Protection of key movements for walking and cycling across a junction.
        - How will this be measured? Junctions treated

    - Sub-category: Low complexity
        - What does this scheme sub-category look like? Minor advantages to enable defensive positioning.
        - How will this be measured? Junctions treated

- New permanent footway
    - Sub-category: High complexity
        - What does this scheme sub-category look like? Large-scale town centre pedestrianisation including area-wide traffic and car parking removal
        - How will this be measured? Miles of footway

    - Sub-category: Medium complexity
        - What does this scheme sub-category look like? Conversion of carriageway to footway on a medium to large scale
        - How will this be measured? Miles of footway

    - Sub-category: Low complexity
        - What does this scheme sub-category look like? Addressing severance in existing walking routes
        - How will this be measured? Miles of footway

- New shared use (walking and cycling) facilities
    - Sub-category: Medium complexity
        - What does this scheme sub-category look like? Provision of a traffic-free rural or suburban route linking settlements as an alternative to hostile road conditions.
        - How will this be measured? Miles

    - Sub-category: Low complexity
        - What does this scheme sub-category look like? An off-road route, for example through parks or green spaces. Schemes should connect settlements and/or tackle severance in walking/cycling networks
        - How will this be measured? Miles

- Improvements to make an existing walking/cycle route safer
    - Sub-category: Medium/high complexity
        - What does this scheme sub-category look like? Use of permanent kerbs, side road treatments, junction improvements for walking/cycling
        - How will this be measured? Miles of improved walking or cycle route, number of improved junctions

    - Sub-category: Low complexity
        - What does this scheme sub-category look like? Installation of infrastructure (for example, wands), or changes to speed limits to improve conditions for walking and cycling.
        - How will this be measured? Miles of improved walking or cycle route, number of improved junctions

- Area-wide traffic management (including by TROs - both permanent and experimental)
    - Sub-category: High complexity
        - What does this scheme sub-category look like? Large-scale, area-wide traffic management in a

- Bus priority measures that also enable active travel (for example, bus gates)
    - Sub-category: Medium complexity
        - What does this scheme sub-category look like? A bus priority measure that significantly improves conditions for walking and cycling as a result (for example, as a result of the bus gate, x miles of road is now suitable for cycling in mixed traffic as described at table 4.1 LTN1/20).
        - How will this be measured? Miles of road improved for walking/cycling

- Provision of secure cycle parking facilities
    - Sub-category: Medium complexity
        - What does this scheme sub-category look like? Large-scale provision of free and publicly accessible on-street cycle parking or secure parking at schools/workplaces/hospitals/transport interchanges
        - How will this be measured? Number of parking spaces

    - Sub-category: Low complexity
        - What does this scheme sub-category look like? Sheffield/Hornsey stands or similar in public places
        - How will this be measured? Number of parking spaces

- New road crossings
    - Sub-category: Low complexity
        - What does this scheme sub-category look like? Crossing addresses a severance issue and will create a continuous walking/cycling route (for example, new signalised crossing of a main road between LTN cells)
        - How will this be measured? Number of new road crossings

    - Sub-category: Low complexity
        - What does this scheme sub-category look like? For example, introducing a pedestrian phase on existing signalised crossing, side road treatments, only if part of high propensity walking route
        - How will this be measured? Number of new road crossings

- Restriction or reduction of car parking availability
    - Sub-category: Low complexity
        - What does this scheme sub-category look like? Introduction of a controlled parking zone in a way that will specifically be of benefit to walking and cycling, including as part of wider scheme proposals for an area. Examples might include the elimination of pavement parking to improve walking connectivity, or as a complimentary traffic management measure to reduce the overall number of car parking spaces and/or reduce commuter parking in residential areas (for example, close to destinations such as shops/NHS sites/transport interchanges).
        - How will this be measured? Miles of footway made accessible, number of parking spaces removed

- School streets
    - Sub-category: Low complexity
        - What does this scheme sub-category look like? Timed restriction of motor vehicle access to a road or roads outside or close to a school, including in rural areas

**Comment by robinlovelace-ate** [comment] 2023-06-19 16:15
Source: https://www.gov.uk/government/publications/how-to-complete-the-active-travel-fund-4-proforma/guidance-note-for-local-authorities-to-support-completion-of-the-active-travel-fund-4-proforma#monitoring-and-evaluation

**Comment by dabreegster** [comment] 2023-09-13 13:51
Duplicate of #336

**Closed by dabreegster** 2023-09-13 13:51 UTC
