### ISSUE TITLE
Issues loading a .TXT file 

### ISSUE THREAD

**Issue by WilliamPhillips-WCC** [acteng/atip#78] opened 2023-02-15 09:16 UTC
I was working on ATIP yesterday and saved by exporting the GeoJSON FILE from the tool.

When trying to load this back in this morning to continue my work it will not load.

I saw from the workshop chat things were "fixed" on this yesterday and also followed the solutions in thread here https://github.com/acteng/atip/issues/72 but it is still not working.

This is what I am getting with the file which was exported yesterday afternoon 

![image](https://user-images.githubusercontent.com/125447325/218983974-7ebdfeee-4293-4a55-8d1c-ef27e4e005d4.png)

And this is what I am getting with the same file that I altered the last two lines of text as suggested here https://github.com/acteng/atip/issues/72 

![image](https://user-images.githubusercontent.com/125447325/218984591-cf9317c3-6eb1-4c69-924b-6cc22bfa832d.png)

I have also attached the two .txt files

[Warwickshire_A47 Hinckley Road.txt](https://github.com/acteng/atip/files/10741344/Warwickshire_A47.Hinckley.Road.txt)

[Warwickshire_A47 Hinckley Road - with edit.txt](https://github.com/acteng/atip/files/10741335/Warwickshire_A47.Hinckley.Road.-.with.edit.txt)

Is there still an issue with the tool or is it somthing our end?

**Comment by dabreegster** [comment] 2023-02-15 10:25
Hi,

I can reproduce this problem. I think you might've gotten unlucky and used the old version (before ~11am yesterday) to start this file and used "Clear all" (triggering the bug), so it was missing some fields. Your edit to fix manually is almost correct; it's just missing a comma at the end of the `"scheme_name": "A47 Hinckley Road"` line.

You can use this corrected file:

[Warwickshire_A47.Hinckley.Road.txt](https://github.com/acteng/atip/files/10741884/Warwickshire_A47.Hinckley.Road.txt)

Sorry for the hassle!

We'll keep this issue open for now. @Sparrow0hawk, maybe we should totally disable the validation of origin fields for now, since more people might also have files missing the field.

**Comment by WilliamPhillips-WCC** [comment] 2023-02-15 10:28
I used the tool from about 2:30pm yesterday if it helps

**Comment by Sparrow0hawk** [comment] 2023-02-15 10:51
@dabreegster would support at this stage rolling back the validation step and looking to re-incorporate in a future release.

**Comment by Robinlovelace** [comment] 2023-02-15 11:42
> @dabreegster would support at this stage rolling back the validation step and looking to re-incorporate in a future release.

:+1:

**Comment by robinlovelace-ate** [comment] 2023-02-16 07:23
Hi @WilliamPhillips-WCC just checking in, has this been fixed? Please report back and close this issue if so, should be fixed on the latest version of the website.

**Comment by WilliamPhillips-WCC** [comment] 2023-02-16 09:13
Hi Robin, Yes all has been resolved and its working perfectly now. Thanks again for all those who have provided help to get this resolved as quickly as you did.

**Closed** 2023-02-16 09:13 UTC
